#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source /usr/local/bin/virtualenvwrapper.sh

# Customize to your needs...
# Set PATH

# Set GOPATH
export GOPATH=~/src/gopath
export PATH=${GOPATH}/bin:$PATH

export EDITOR=vim
unsetopt correct_all
export COPYFILE_DISABLE=true
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu
bindkey '^X^X' history-beginning-search-menu
bindkey -M viins '^R' history-incremental-search-backward
bindkey -M vicmd '^R' history-incremental-search-backward
bindkey -v

alias watch='watch -c'
alias k=kubectl

# Set default virtualenv
workon devco

# Alias to print out all git aliases
alias sga='cat ~/.zprezto/modules/git/alias.zsh'

alias git=hub

eval "$(rbenv init -)"

finder_showall() {
 defaults write com.apple.finder AppleShowAllFiles ${1}
 killall Finder
}

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# If kubectl is installed, run shell completion function
if hash kubectl 2> /dev/null; then
 source <(kubectl completion zsh)
fi
alias ctx='kubectl config use-context'

# Set Drone related env vars
source ~/.drone

setopt auto_cd
cdpath=($HOME/src)

kssh() {
  POD=$1
  ip=$(kubectl get pods $POD -o jsonpath='{.status.hostIP}')
  if [ $? -ne '0' ] ; then
    exit 1
  fi
  ssh $ip
}

nodessh() {
  NODE=$1
  ip=$(kubectl get node $NODE -o json | jq -r '.status.addresses | map(select(.type == "InternalIP"))[0] | .address')
   if [ $? -ne '0' ] ; then
    exit 1
  fi
  ssh $ip
} 

